<a href="https://colab.research.google.com/github/mayurpophale/data_science/blob/main/anime_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [42]:
import numpy as np
import pandas as pd

In [43]:
df = pd.read_csv(r"/content/anime.csv")

In [44]:
df.head()

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [45]:
df.loc[2]['Title']

'Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 - Dec 2022474,138 members'

In [46]:
def extract_episodas(txt):
  data = ''
  check = False
  for i in txt:
    if i == ')':
      check = False
      return data
    if check == True:
      data +=i
    if i == '(':
      check = True


df["eps"]=df["Title"].apply(extract_episodas)

In [47]:
df.head()

   Rank                                              Title  Score     eps
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10  64 eps
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07  24 eps
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06  13 eps
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06  51 eps
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05  10 eps

In [48]:
#make a new column for episode count
df['eps'] = df['eps'].str.replace(" eps",'').astype(int)

In [49]:
df.head()

   Rank                                              Title  Score  eps
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10   64
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07   24
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06   13
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06   51
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05   10

In [50]:
#make a new column for time stamp
df['Title'][0]

'Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr 2009 - Jul 20103,218,472 membersManga StoreVolume 1€4.58Preview'

In [51]:
def extract_time(txt):
  check = False
  data = ''
  for i in range(len(txt)):
    if txt[i] == ')':
      for j in range(i+1,i+20):
        data+=txt[j]
      return data
df["Time Stamp"]=df["Title"].apply(extract_time)

In [52]:
df.head()

,Rank,Title,Score,eps,Time Stamp
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019

In [53]:
dates = df['Time Stamp'].str.split(' - ', expand=True)

start = pd.to_datetime(dates[0], format='%b %Y', errors='coerce')

end = dates[1].replace('Present', pd.Timestamp.today().strftime('%b %Y'))
end = pd.to_datetime(end, format='%b %Y', errors='coerce')

df['Months'] = (
    (end.dt.year - start.dt.year) * 12
    + (end.dt.month - start.dt.month)
    + 1
)

In [54]:
df.head()

,Rank,Title,Score,eps,Time Stamp,Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,16
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,6
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,3
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,12
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,4

In [55]:
#which anime has the highest score

In [56]:
df[df['Score']==df['Score'].max()]

,Rank,Title,Score,eps,Time Stamp,Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.1,64,Apr 2009 - Jul 2010,16

In [57]:
#give me top 5 highest scoring anime
df['Title'].head()

0    Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...
1    Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...
2    Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...
3    Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...
4    Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...
Name: Title, dtype: object

In [58]:

#which is the longest running anime

In [59]:
#which anime has the highest episode count
df[df['eps']==df['eps'].max()]

,Rank,Title,Score,eps,Time Stamp,Months
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010,48

In [60]:
#animes with top 5 episode count
df.sort_values(by='eps',ascending=False).head()

,Rank,Title,Score,eps,Time Stamp,Months
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010,48
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,148,Oct 2011 - Sep 2014,36
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Jan 1988 - Mar 1997,111
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,75,Oct 2000 - Mar 2002,18
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,74,Apr 2004 - Sep 2005,18

In [61]:
#which is the longest running anime
df[df['Months']==df['Months'].max()]

,Rank,Title,Score,eps,Time Stamp,Months
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Jan 1988 - Mar 1997,111