<a href="https://colab.research.google.com/github/mayurpophale/data_science/blob/main/modeltuning(hyperparameter).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
df = sns.load_dataset("iris")

In [2]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [6]:
from sklearn.model_selection import train_test_split
X = df.drop('species', axis=1)
y = df['species']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [13]:
from sklearn.neighbors import KNeighborsClassifier
model_knn = KNeighborsClassifier(n_neighbors=2)

In [14]:
model_knn.fit(X_train, y_train)
model_knn.score(X_test, y_test)

1.0

In [23]:
from sklearn.svm import SVC
model_svc = SVC()
model_svc.fit(X_train, y_train)
model_svc.score(X_test, y_test)

1.0

## Grid Search CV

In [20]:
from sklearn.model_selection import GridSearchCV

In [24]:
classifier = GridSearchCV(SVC(), {
    'C': [1,10,20],
    'kernel': ['rbf','linear']
}, cv=5, return_train_score=False)
classifier.fit(X, y)

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [1, 10, 20], 'kernel': ['rbf', 'linear']})

In [25]:
results = pd.DataFrame(classifier.cv_results_)
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.010185,0.001650,0.005682,0.001701,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,0.966667,0.966667,0.933333,1.0,0.966667,0.021082,5
1,0.011373,0.003049,0.006351,0.003064,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.005676,0.003435,0.003427,0.001048,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.006440,0.001450,0.004746,0.001946,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.007621,0.003427,0.004654,0.002062,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
5,0.009908,0.004509,0.007115,0.001739,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,5

In [26]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.966667
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.980000
5       20       linear         0.966667

## Random Serach CV

In [27]:
from sklearn.model_selection import RandomizedSearchCV

In [28]:
classifier_r = RandomizedSearchCV(SVC(), {
    'C': [1,10,20],
    'kernel': ['rbf','linear']
}, cv=5, return_train_score=False, n_iter=4)

In [29]:
classifier_r.fit(X, y)

RandomizedSearchCV(cv=5, estimator=SVC(), n_iter=4,
                   param_distributions={'C': [1, 10, 20],
                                        'kernel': ['rbf', 'linear']})

In [30]:
results_r = pd.DataFrame(classifier_r.cv_results_)
results_r

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.027809,0.003986,0.020225,0.004073,rbf,1,"{'kernel': 'rbf', 'C': 1}",0.966667,0.966667,0.966667,0.933333,1.0,0.966667,0.021082,4
1,0.029773,0.009427,0.016406,0.004198,rbf,20,"{'kernel': 'rbf', 'C': 20}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.027685,0.004903,0.017428,0.005441,linear,10,"{'kernel': 'linear', 'C': 10}",1.000000,1.000000,0.900000,0.966667,1.0,0.973333,0.038873,3
3,0.029546,0.005294,0.019940,0.006381,rbf,10,"{'kernel': 'rbf', 'C': 10}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1

In [31]:
results_r[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.966667
1       20          rbf         0.980000
2       10       linear         0.973333
3       10          rbf         0.980000